-- Import Chips and Savory Snacks
INSERT INTO master_items (name, type, brand, suggested_price, suggested_cost, popularity, shelf_life, is_seasonal, is_imported, is_healthy, category, status) VALUES
-- CHIPS (SMALL BAGS)
('Ruffles All Dressed', 'snack', 'Ruffles', 1.50, 0.86, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Ruffles Sour Cream', 'snack', 'Ruffles', 1.50, 0.90, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Ruffles Cheddar', 'snack', 'Ruffles', 1.50, 0.90, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Ruffles BBQ', 'snack', 'Ruffles', 1.50, 0.90, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Doritos Nacho', 'snack', 'Doritos', 1.50, 0.90, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Doritos Zesty', 'snack', 'Doritos', 1.50, 0.91, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Doritos Cool Ranch', 'snack', 'Doritos', 1.50, 0.91, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Doritos Spicy Nacho', 'snack', 'Doritos', 1.50, 0.91, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Doritos Sweet Chili Heat', 'snack', 'Doritos', 1.50, 0.91, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Lays Classic', 'snack', 'Lays', 1.50, 0.84, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Lays BBQ', 'snack', 'Lays', 1.50, 0.84, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Lays Salt & Vinegar', 'snack', 'Lays', 1.50, 0.84, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Lays Ketchup', 'snack', 'Lays', 1.50, 0.84, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Lays Dill Pickle', 'snack', 'Lays', 1.50, 0.84, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Lays Sour Cream & Onion', 'snack', 'Lays', 1.50, 0.84, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Miss Vickies Original', 'snack', 'Miss Vickies', 1.50, 0.84, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Miss Vickies Sweet Chili', 'snack', 'Miss Vickies', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Miss Vickies Jalapeno', 'snack', 'Miss Vickies', 1.50, 0.83, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Miss Vickies Sea Salt & Malt Vinegar', 'snack', 'Miss Vickies', 1.50, 0.83, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Miss Vickies Spicy Dill Pickle', 'snack', 'Miss Vickies', 1.50, 0.83, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Crunchy', 'snack', 'Cheetos', 1.50, 0.93, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Jalapeno', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Puffs', 'snack', 'Cheetos', 1.50, 0.93, 'high', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Flamin Hot', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Flamin Hot Puffs', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos White Cheddar', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos White Cheddar Puffs', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Crunchy Flamin Hot', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Crunchy Jalapeno', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'),
('Cheetos Crunchy White Cheddar', 'snack', 'Cheetos', 1.50, 0.93, 'medium', 180, 0, 0, 0, 'Chips and Savory Snacks', 'active'); 