-- Import Candy and Chocolate Bars (Part 2)
INSERT INTO master_items (name, type, brand, suggested_price, suggested_cost, popularity, shelf_life, is_seasonal, is_imported, is_healthy, category, status) VALUES
('Crunch Bar', 'snack', 'Nestle', 1.25, 0.90, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Dark Chocolate', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Milk Chocolate', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Caramel', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Almond', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Mint', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Raspberry', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Strawberry', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Vanilla', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove White Chocolate', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Dark Chocolate Promises', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Milk Chocolate Promises', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Caramel Promises', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Almond Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Mint Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Raspberry Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Strawberry Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Vanilla Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove White Chocolate Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Dark Chocolate Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Milk Chocolate Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Caramel Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Almond Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Mint Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Raspberry Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Strawberry Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Vanilla Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove White Chocolate Silky Smooth', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Dark Chocolate Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Milk Chocolate Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Caramel Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'high', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Almond Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Mint Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Raspberry Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Strawberry Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove Vanilla Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'),
('Dove White Chocolate Silky Smooth Promises', 'snack', 'Dove', 1.25, 0.95, 'medium', 180, 0, 0, 0, 'Candy and Chocolate Bars', 'active'); 