-- Import Candy and Chocolate Bars (Part 1)
INSERT INTO items (machine_id, name, type, price, list_type, status) VALUES
-- CANDY & CHOCOLATE BARS
(1, '3 Musketeers Bar', 'snack', 1.25, 'regular', 'active'),
(1, 'Aero (Milk Chocolate)', 'snack', 1.25, 'regular', 'active'),
(1, 'Aero (Mint)', 'snack', 1.25, 'regular', 'active'),
(1, 'Aero (Bubbles)', 'snack', 1.25, 'regular', 'active'),
(1, 'Baby Ruth', 'snack', 1.25, 'regular', 'active'),
(1, 'Butterfinger', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Caramilk', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Caramel)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Fruit & Nut)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Hazelnut)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Orange)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Roast Almond)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Turkish Delight)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Dairy Milk (Wispa)', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Flake', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Picnic', 'snack', 1.25, 'regular', 'active'),
(1, 'Cadbury Wunderbar', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Dark)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (White)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Hazelnut)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Sea Salt)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Caramel)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Milk Chocolate)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Dark Chocolate)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (White Chocolate)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Hazelnut Chocolate)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Sea Salt Chocolate)', 'snack', 1.25, 'regular', 'active'),
(1, 'Caramilk (Caramel Chocolate)', 'snack', 1.25, 'regular', 'active'); 