<?php
return [
    'default_options' => [
        'size' => 300,
        'margin' => 10,
        'error_correction_level' => 'H',
        'foreground_color' => '#000000',
        'background_color' => '#FFFFFF',
        'output_format' => 'svg',
        'module_shape' => 'square',
        'module_size' => 1,
        'module_spacing' => 0,
        'module_glow' => false,
        'module_glow_color' => '#000000',
        'module_glow_intensity' => 5,
        'gradient_type' => 'none',
        'gradient_start' => '#000000',
        'gradient_end' => '#0000FF',
        'gradient_angle' => 45,
        'gradient_opacity' => 1,
        'gradient_stops' => [],
        'eye_style' => 'square',
        'eye_color' => '#000000',
        'eye_size' => 1,
        'eye_border' => false,
        'eye_border_color' => '#000000',
        'eye_border_width' => 1,
        'eye_glow' => false,
        'eye_glow_color' => '#000000',
        'eye_glow_intensity' => 5,
        'frame_style' => 'none',
        'frame_color' => '#000000',
        'frame_width' => 2,
        'frame_radius' => 5,
        'frame_glow' => false,
        'frame_glow_color' => '#000000',
        'frame_glow_intensity' => 5,
        'label_text' => '',
        'label_font' => 'Arial',
        'label_size' => 12,
        'label_color' => '#000000',
        'label_alignment' => 'center',
        'label_glow' => false,
        'label_glow_color' => '#000000',
        'label_glow_intensity' => 5,
        'label_rotation' => 0,
        'bottom_text' => '',
        'bottom_font' => 'Arial',
        'bottom_size' => 12,
        'bottom_color' => '#000000',
        'bottom_alignment' => 'center',
        'bottom_glow' => false,
        'bottom_glow_color' => '#000000',
        'bottom_glow_intensity' => 5,
        'bottom_rotation' => 0,
        'shadow' => false,
        'shadow_color' => '#000000',
        'shadow_blur' => 5,
        'shadow_offset_x' => 2,
        'shadow_offset_y' => 2,
        'shadow_opacity' => 0.5,
        'enable_stats' => false,
        'stats_display' => 'none'
    ],
    'allowed_types' => [
        'static',
        'dynamic',
        'dynamic_voting',
        'dynamic_vending',
        'machine_sales',
        'promotion',
        'cross_promo',
        'stackable'
    ],
    'output_formats' => ['svg', 'png'],
    'max_size' => 1000,
    'min_size' => 100,
    'allowed_colors' => [
        'foreground_color',
        'background_color',
        'module_glow_color',
        'gradient_start',
        'gradient_end',
        'eye_color',
        'eye_border_color',
        'eye_glow_color',
        'frame_color',
        'frame_glow_color',
        'label_color',
        'label_glow_color',
        'bottom_color',
        'bottom_glow_color',
        'shadow_color'
    ],
    'allowed_fonts' => [
        'Arial',
        'Helvetica',
        'Times New Roman',
        'Courier New',
        'Georgia',
        'Verdana'
    ],
    'allowed_eye_styles' => [
        'square',
        'rounded',
        'circular',
        'diamond',
        'leaf'
    ],
    'allowed_frame_styles' => [
        'none',
        'solid',
        'dashed',
        'dotted',
        'double'
    ],
    'allowed_gradient_types' => [
        'none',
        'linear',
        'radial',
        'diagonal'
    ]
]; 